// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoRapido.Infra.Data.Context;

namespace ProjetoRapido.Infra.Data.Migrations
{
    [DbContext(typeof(ProjetoRapidoContext))]
    [Migration("20190106184702_Criando-Banco-Dados")]
    partial class CriandoBancoDados
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoRapido.Infra.Data.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EnderecoID");

                    b.Property<string>("Nome")
                        .HasMaxLength(80);

                    b.Property<string>("SobreNome")
                        .HasMaxLength(100);

                    b.HasKey("ClienteID");

                    b.HasIndex("EnderecoID");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("ProjetoRapido.Infra.Data.Entities.Endereco", b =>
                {
                    b.Property<int>("EnderecoID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasMaxLength(100);

                    b.Property<string>("Cidade")
                        .HasMaxLength(100);

                    b.Property<string>("Estado")
                        .HasMaxLength(50);

                    b.Property<string>("Logradouro")
                        .HasMaxLength(150);

                    b.Property<string>("Numero")
                        .HasMaxLength(10);

                    b.HasKey("EnderecoID");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("ProjetoRapido.Infra.Data.Entities.Cliente", b =>
                {
                    b.HasOne("ProjetoRapido.Infra.Data.Entities.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
